#Привет! Это конфиг плагина,
#Для изменения значения того, сколько секунд должно пройти до того как сервер перезапуститься после Прописанной команды!

restart-timer: 20 #20 секунд
restart-text: "§l§fРестарт через " #тут ты можешь настроить текст который будет показываться при старте перезапуска
restart-end: "§l§fУвидимся после перезапуска!" #тут можно настроить текст после окончания таймера перезапуска
restart-canel: "Перезапуск отменен!" #тут можно настроить текст, который будет писаться после ручной отменя перезапуска!