name: RestartCommand_MrFaiergm_SRVPLG
version: '1.0-SNAPSHOT'
main: org.mrfaiergm_studios.restartCommand_MrFaiergm_SRVPLG.RestartCommand_MrFaiergm_SRVPLG
api-version: '26.2'
authors: [ MrFaiergm ]
website: https://t.me/mrfaiergmchanel
description: Plugin for server management

commands:
  pstop:
    description: Остановить перезапуск сервера
    permission: mrfaiergm.admin
  prestart:
    description: Запустить перезапуск сервера
    permission: mrfaiergm.admin